/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/charts/index" |
  "/pages/demo/index" |
  "/pages/home/index" |
  "/pages/mine/index" |
  "/subPages/adminer/analysis" |
  "/subPages/adminer/index" |
  "/subPages/adminer/mine" |
  "/subPages/ci/index" |
  "/subPages/create-uni/index" |
  "/subPages/feedback/index" |
  "/subPages/icon/index" |
  "/subPages/pinia/index" |
  "/subPages/request/index" |
  "/subPages/router/demo-aftereach" |
  "/subPages/router/demo-guard" |
  "/subPages/router/demo-object" |
  "/subPages/router/demo-params" |
  "/subPages/router/demo-protected" |
  "/subPages/router/demo-query" |
  "/subPages/router/demo-string" |
  "/subPages/router/index" |
  "/subPages/skills/index" |
  "/subPages/styles/index" |
  "/subPages/uni-ku-root/index" |
  "/subPages/adminer/about/index" |
  "/subPages/adminer/inventory/index" |
  "/subPages/adminer/orders/index" |
  "/subPages/adminer/settings/index" |
  "/subPages/adminer/farmer/add/index" |
  "/subPages/adminer/hotel/add/index" |
  "/subPages/adminer/purchase/add/index" |
  "/subPages/adminer/sale/add/index" |
  "/subEcharts/echarts/index" |
  "/subAsyncEcharts/asyncEcharts/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/charts/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
